name: dev-build
run-name: Build plugin for development
on: [push, workflow_dispatch]
jobs:
  build-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup latest Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Setup latest PNPM
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Update decky-frontend-lib
        run: pnpm update decky-frontend-lib --latest

      - name: Build frontend from source
        run: |
          pnpm i
          pnpm run build

      - name: Download Decky Plugin CLI
        run: |
          mkdir $(pwd)/cli
          curl -L -o $(pwd)/cli/decky "https://github.com/SteamDeckHomebrew/cli/releases/latest/download/decky-linux-x86_64"
          chmod +x $(pwd)/cli/decky

      - name: Build plugin
        run: |
          $(pwd)/cli/decky plugin build $(pwd) --build-as-root
          unzip out/Hello\ Decky.zip -d out/Hello\ Decky

      - name: Set outputs
        id: vars
        run: echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Upload plugin
        uses: actions/upload-artifact@v4
        with:
          name: Hello Decky-${{ steps.vars.outputs.SHA_SHORT }}
          path: out/Hello Decky/*
          compression-level: 9
